# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.app_request:
        class: AppBundle\EventListener\AppRequestListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    handler_gateway:
        class:        SourceBundle\Base\HandlerGateway
        arguments: ['@service_container']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
